### ISSUE TITLE
Add trop+strat chemistry scheme

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/CAM#100]
### What is the feature/what would you like to discuss?

Add a new chemistry scheme that covers both the troposphere and stratosphere for the NorESM2.3 release.
Note, this scheme will include both [bromoform](https://github.com/NorESMhub/CAM/issues/99) and [explicit volcanic emissions](https://github.com/NorESMhub/CAM/issues/101).

### Will this change (regression test) answers?

A new regression test will be introduced

### Will you be implementing this enhancement yourself?

No

**Comment by oyvindseland** [comment]
Can be closed since the PR has completed?

**Comment by DirkOlivie** [comment]
Hi Øyvind, yes can be closed.  Best regards, Dirk
