### ISSUE TITLE
Aerosol dry deposition bug

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/CAM#111]
### What happened?

Error in the calculation of the dry deposition.

### What are the steps to reproduce the bug?

Run standard NorESM2

### What CAM-Nor tag were you using?

cam_cesm2_1_rel_05-Nor_v1.0.5

### What machine were you running CAM (or NorESM) on?

Betzy

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

No

### Extra info

The subroutine oslo_aero_dry_intr in the file src/chemistry/oslo_aero/oslo_aerosols_intr.F90 should be modified.

The corrected code should look like (old code commented out) :
```fortran
       rad_aer(1:ncol,top_lev:) = 0.5_r8*dgncur_awet(1:ncol,top_lev:,m)  
!                         *exp(1.5_r8*(logSigma))
	                   *exp(1.5_r8*(logSigma**2))
		...
        rad_aer(1:ncol,top_lev:) = 0.5_r8*dgncur_awet_processmode(1:ncol,top_lev:,processModeMap(mm))
!	                     *exp(1.5_r8*(logSigma))
                            *exp(1.5_r8*(logSigma**2))
```

**Comment by gold2718** [comment]
Closed by #119
