### ISSUE TITLE
New tests to add for noresm2.1. release

### ISSUE THREAD

**Issue by mvertens** [NorESMhub/CAM#114]
### What is the feature/what would you like to discuss?

New tests needed for the noresm2.1 release are the following:

**"Stand-alone CAM" (F compsets):**
3 compsets, 2 resolutions

- platform betzy for all, fram for just f19_f19
- Test resolutions: f19_f19, f09_f09 (NOTE: the mask is set to gx1v6 - but the domain files use mtn14)
- Test types ERP, SMS_D,PFS
- NF1850norbc for f19_f19, NF1850frc2norbc for f09_f09 (N1850 model SST + forcing from 1850)
- NF1850norbc_aer2014 for f19_f19, NF1850frc2norbc_aer2014 for f09_f09 (N1850 model SST + forcing from 1850, except aerosols from 2014 emissions)
- NFHISTnorpddmsbc for f09_f09

### Is there anyone in particular you want to be part of this conversation?

@gold2718 

### Will this change (regression test) answers?

There are no regressions tests yet - so this will introduce regression testing.

### Will you be implementing this enhancement yourself?

Yes

**Comment by gold2718** [comment]
Resolved in #116
