### ISSUE TITLE
Allow revert ice delimiter fix

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/CAM#124]
### Issue Description

The ice delimiter bug correction implemented in response to #110 leaves the model in an unbalanced state that requires tuning to fix. For the NorESM2.1 release, we will leave this correction in the code but include a compile-time option to revert this change so that the results are more in line with the NorESM2.0 release.

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

**Comment by MichaelSchulzMETNO** [comment]
hm - Why should the bug be reintroduced? I thought retuning will be suggested after some testing.

**Comment by gold2718** [comment]
Resolved by #125
