### ISSUE TITLE
Lots of compsets can not be run with the alias

### ISSUE THREAD

**Issue by astridbg** [NorESMhub/CAM#147]
### What happened?

Due to the change in component names `CAM60%PTAERO`->`CAM60%NORESM` some comsets (f.e. `NF2000climo`) can not be run from alias since `CAM60%PTAERO` does not exist anymore.

### What are the steps to reproduce the bug?

1. Checkout `cam_cesm2_1_rel_05-Nor_v1.0.6` or `cam_cesm2_1_rel_05-Nor_v1.0.7`.
2. Create new case with NF2000climo compset

### What CAM-Nor tag were you using?

cam_cesm2_1_rel_05-Nor_v1.0.6

### What machine were you running CAM (or NorESM) on?

Betzy

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Yes

### Extra info

should I just try to replace %PTAERO with %NORESM in all the relevant aliases? (Also in NorESM)??

**Comment by gold2718** [comment]
Hi @astridbg, 

These bugs have been around for a long time as these are NorESM2.0 release tags.
Is there a reason you need these tags? Could you instead NorESM2.1 (NorESM tag, release-noresm2.1.1 which uses CAM tag cam_noresm2_1_v1.0.2)?

With the release of NorESM2.1, there are no planned updates to NorESM2.0. Please let me know if you need help moving to NorESM2.1.

**Comment by astridbg** [comment]
I see, thank you for the explanation!
