### ISSUE TITLE
P0 always needs to be on history file

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/CAM#150]
### What happened?

In prototype NorESM2.5 (e.g. `noresm_v11_cam6_3_123`), `P0` is not showing up on CAM history files.

### What are the steps to reproduce the bug?

Run a CAM-SE simulation using `noresm_v11_cam6_3_123`, look at history files.

### What CAM-Nor tag were you using?

noresm_v11_cam6_3_123

### What machine were you running CAM (or NorESM) on?

Betzy

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

No

**Comment by adagj** [comment]
Did we decide that P0 doesn't need to be on history files with SE?

**Comment by MichaelSchulzMETNO** [comment]
Yes - my understanding is, that it does not make sense to be put on the raw output files.

**Comment by gold2718** [comment]
Agree. For background, see [this comment](https://github.com/NorESMhub/CAM/issues/146#issuecomment-2159255329) and below in #146.
