### ISSUE TITLE
Add namelist options for the cloud water / cloud ice tuning included from the KeyClim simulations

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/CAM#156]
### Issue Type

Code Clean-up

### Issue Description

The parameter values used in KeyClim simulations were only first guesses / tests and should be tuned. This is easier if they can be defined / specified in the namelist

### Will this change answers?

No

### Will you be implementing this yourself?

No

**Comment by DirkOlivie** [comment]
Does this need explicit namelist options?  Cannot this just be the default?

**Comment by gold2718** [comment]
It might help if the parameters under discussion were listed here. I think the idea is to turn certain constants in the code into namelist options with the default value being the value from the KeyClim simulation code base. @oyvindseland , which constants do you see as good candidates for this treatment?

**Comment by oyvindseland** [comment]
The factors are included
