### ISSUE TITLE
NorESM2.3 : Tag/branch for OSLO_AERO in Externals_CAM.cfg

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/CAM#159]
### Issue Type

Externals Update

### Issue Description

@gold2718 @mvertens @oyvindseland 

During the process of making NorESM2.3, we use branches called _noresm2_3_develop_ in the 3 repositories (NorESM, CAM, OSLO_AERO).

When you are in the _noresm2_3_develop_ branch of NorESM : in the NorESM/Externals.cfg file, CAM is referenced by the branch _noresm2_3_develop_.  This looks ok.
However, when you are in the _noresm2_3_develop_ branch of CAM : in Externals_CAM.cfg, OSLO_AERO is still reference by a tag (_oslo_aero_2_3a1_), and not the branch _noresm2_3_develop_ which I would have expected.

Is there a  reason for this?

I thought that during this process of making NorESM2.3, we would work with branches (which are moving targets when PR are coming in and accepted).  Only at the end of the whole process, we would go back to tags.  Possibly I see this wrong.

Best regards, Dirk

### Will this change answers?

No

### Will you be implementing this yourself?

Yes, but I will need some help

**Comment by oyvindseland** [comment]
The reason why I brought this up with Dirk is that I want to make a change in oslo_aero only.  If the Externals_CAM point to a tag I need to make a branch and a pull request to CAM_develop just to update the externals file. I though that pointing to a tag in a development branch should just be done for any components that should not be changed?

**Comment by oyvindseland** [comment]
It looks like I need to go with the tag and create CAM_branch with Externals_CAM.   
The noresm_develop branch in oslo_aero does not compile

**Comment by mvertens** [comment]
For noresm2_3 you need to use the noresm2_3_develop branch not noresm_develop

**Comment by oyvindseland** [comment]
Should have seen that. Compiles now

**Comment by MichaelSchulzMETNO** [comment]
To see if a tag is on a branch use eg: 
git branch  --contains oslo_aero_2_3a1
when being on the repository in question.
In our case the tag is in the right branch.

**Comment by oyvindseland** [comment]
Yes I know that I started with a  tag, the question was more if that everyone should start from a tag in which all branches has to be merged individually into the development branch later or if the development should be done from the development branch in which the developer must merge the new development updates but can then make a pull request into the development branch.

**Comment by MichaelSchulzMETNO** [comment]
The confusing thing is, a tag can be on several branches or just one. Its good to check on which it is. Anyway - pull requests should be directed to the noresm2_3_develop branch. If Externals_CAM.cfg is pointing just to the Oslo-aer tag, then you will not see your changes in Oslo-aer. So there is some dependency of CAM and Oslo-aer now. If Externals_CAM.cfg points to the noresm2_3_develop branch in Oslo-aer, it will always use the head.

**Comment by gold2718** [comment]
Given the confusion, I think all CAM PRs should point to either a tag or a hash of OSLO_AERO. We can use hashes to avoid adding too many quick development tags while still maintaining consistency between a CAM commit and the associated OSLO_AERO version.
Any objections?

**Comment by oyvindseland** [comment]
Since the discussion is included I presume this issue can be closed? @gold2718

**Comment by gold2718** [comment]
> Since the discussion is included I presume this issue can be closed? @gold2718

Agreed and also we have moved into the alpha stage so everything is tagged.
