### ISSUE TITLE
CCN calculations seem to be wrong?

### ISSUE THREAD

**Issue by sarambl** [NorESMhub/CAM#25]
I was looking at my runs with the latest release (release-noresm2.0.1) and I noticed that the CCN values seem to be very weird. Basically they seem to have the same pattern at all supersaturations (see plots) ( (CCNx/CCNy) is constant everywhere.) 

![image](https://user-images.githubusercontent.com/17406708/84507663-7a600480-acc1-11ea-9f69-2fcb8fb3334e.png)
(same pattern is true of all CCNx)

I emailed with @oyvindseland (cc @Kirkevag @DirkOlivie) about this and @oyvindseland confirmed this in his results (so it's probably not that I messed up my version). 

Does anyone have an idea what might have caused this? Are there any plans to look into it?

**Comment by oyvindseland** [comment]
Hi 

I looked into a bit more although only from a debugging point of view. (Just used month 1 of a simulation)

And the pattern is similar but not identical, so it may actually be a feature of the model.
Just looking at the pattern can be a bit misleading though.
There are areas, e.g. the Arctic in which the relative difference between CCN at different supersaturations is much larger. 
CCN4 / CCN7 is 4 times as large in the Arctic as in the tropical region for this single month.

It need much more detailed analysis and I have not looked into the code yet. The pattern does follow the nucleation pattern a bit too much to my liking so I still need to check if it summarizes correctly all mixtures.

**Comment by sarambl** [comment]
Hi @oyvindseland ! Cool that you had a look! 
It's been a while since I had a look at this, so I don't remember exactly, but the most important reason I didn't find it very plausible was actually that I was comparing different model runs the change in CCN was not at all comparable with the same runs for the development version of CAM5.??-Oslo and that it didn't make much sense in terms of CDNC. I will, however, double check this now, since I have now a much better understanding of the activation in the model.

**Comment by oyvindseland** [comment]
Actually I think I found the error now.  
As far as I can see it is actually CCN only from biomass burning without condensate, i.e. mixture 14 not 1.

During the last minute testing of CMIP6 set-up we tried to fix some errors in the initialisation. I saw now that Thomas put the if test (if zero aerosol then CCN=0), while it should have been (if zero aerosols then CCN=CCN+0)

Since mixture 13 is zero everything became zero except for mixture 14.

You can see it in   in the end of the subroutine ccncalc_oslo within ndrop.F90.

**Comment by sarambl** [comment]
Did a very quick one-month check now between two runs with different NPF parameterization and the relative change ((PERT-CTRL)/CTRL) is the same for all CCNx -- which doesn't make sense because the distribution should be different and the CDNC is... 
Mostly it looks like N_AER or NCONC01/NNAT_1, but not quite that either.

**Comment by oyvindseland** [comment]
As I described above that is why i think it is actually NNat_14

**Comment by sarambl** [comment]
Ah, exactly! The relative change in CCNx is actually perfectly that of NCONC14. Then I think we can settle that it is in fact a bug, and what's more we have a pretty good idea where to start fixing it? 
I can always have a look at it with time, but I am extremely busy at the moment, so would have to be later.

**Comment by oyvindseland** [comment]
Corrected bug. It does not change the results of the model but would like to do a restart test to make sure before I submit anything.

Added a simple ncview comparison for the first month for CCN 1%. Same intervall in both plots

![image](https://user-images.githubusercontent.com/15869190/100095668-243fe180-2e5b-11eb-88cf-e8b585ba2177.png)

![image](https://user-images.githubusercontent.com/15869190/100095608-0e322100-2e5b-11eb-942c-c9ea49930493.png)

**Comment by oyvindseland** [comment]
The corrected version is still not included in the github version, Will do so

**Comment by MichaelSchulzMETNO** [comment]
To be updated in all NorESM2-CAM6Nor branches @oyvindseland

**Comment by oyvindseland** [comment]
Pull request sent for CAM-Nor development branch.

**Comment by gold2718** [comment]
Fixed in active branches.
