### ISSUE TITLE
Observed SSTs and sea-ice concentration to drive CAM-Nor for  the year 2018

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/CAM#26]
Currently there is no SST dataset available for  2018 on  https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/atm/cam/sst/  to drive CAM or CAM-Nor simulations. Might they become available in the near future?  Might we get them from somewhere else?
(for 2016 they became available mid-2017, for  2017 in mid-2018.  However 2018 and 2019 are still not available).

**Comment by oyvindseland** [comment]
Will check if any new data is avaialble on cheyenne.

**Comment by oyvindseland** [comment]
Data copied to Norwegian HPC
