### ISSUE TITLE
COSP MODIS effective radius bug

### ISSUE THREAD

**Issue by annlew** [NorESMhub/CAM#58]
Different LUTs are used for calculating the NIR albedo for model r_eff and cosp r_eff:

cosp_optics.F90 
USE MOD_MODIS_SIM, ONLY: phaseIsLiquid,phaseIsIce,get_g_nir=>get_g_nir_old,get_ssa_nir=>get_ssa_nir_old

Fixed in CESM2.2

**Comment by DirkOlivie** [comment]
The bugfix is now included in branch cam-Nor-dev.  I will also include it in cam_cesm_2_1_rel05-Nor (which is the branch used in the CMIP6 version of  NorESM2 (noresm2)).

**Comment by gold2718** [comment]
Closing as this fix was entered into that branch (see below).
```
commit de43efe5936d250b9d59e7697d487eee5822a8c7
Author: DirkOlivie <dirk.olivie@met.no>
Date:   Mon Nov 21 13:02:48 2022 +0100
```
