### ISSUE TITLE
Possible removal / test  of iterative process for dry deposition and emissions

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/CAM#63]
Due to the high dry deposition of coarse mode particles in NorESM, there is an additional parameterisation combining dry deposition and emissions in one equation. This was done to reduce the sea-saw pattern in concentrations that can be found when large emissions is followed by large deposition. This sea-saw pattern was likely exaggerated by the error in dry deposition which is now corrected
The parameterisation can be found in oslo_aerosols_intr.F90

**Describe the solution you would like to see**
We should consider removing the addtional parameterisation at least for a sensitivity test to check how important it is for the budget and for understanding differences compared to standard CAM

**Comment by oyvindseland** [comment]
I agree with the moving into the to do list. 
I am even uncertain if it made the move from NorESM-CAM5.x into the CMIP6 version.

should probably just close the issue here.

**Comment by gold2718** [comment]
Information out of date, closing.

**Comment by oyvindseland** [comment]
This feature is included in NorESM2. It does not however interfere with the correction of dry deposition bug since the test explicitly test the loss fraction from the dry deposition. If the loss term from the dry deposition is greater than  1 % of the concentration then there is an logaritmic calculation of the loss. Reopens partly to document that it is not out of date, but will wait to close it until I am  certain that the reduced height of the boundary layer does not interfere with the solution / stability of the equation

**Comment by oyvindseland** [comment]
The relevant subroutine in oslo_aero is oslo_aero_depos.F90

**Comment by oyvindseland** [comment]
This feature created double counting of emissions of NorESM2.5 and is removed from the development branch. Closing issue
