### ISSUE TITLE
Missing information in README

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/CAM#86]
The README file in the main branch is missing descriptions for two NorESM/CAM tags; cam_cesm2_1_rel_05-Nor_v1.0.3 and cam_cesm2_1_rel_05-Nor_v1.0.4.

Suggested for descriptions
- cam_cesm2_1_rel_05-Nor_v1.0.3: New use cases and a microphysics bug fix
- cam_cesm2_1_rel_05-Nor_v1.0.4: Improved configuration for production tagged aerosols

**Comment by DirkOlivie** [comment]
Hi Steve,

cam_cesm2_1_rel_05-Nor_v1.0.4 : two files had changed (README.md and cime_config/config_component.xml).  The last change guaranteed automatic download of AeroTab files for PTAERO compsets.
Maybe call it : automatic download of AeroTab files for PTAERO compsets

cam_cesm2_1_rel_05-Nor_v1.0.4 : only one file had changed (cime_config/config_component.xml).  To allow for some coupled N2000_CAM6%NORESM compsets.
Maybe call it : allowing coupled N2000_CAM6%NORESM compsets

Best regards

**Comment by gold2718** [comment]
For the record:
```
$ git diff --name-only cam_cesm2_1_rel_05-Nor_v1.0.2 cam_cesm2_1_rel_05-Nor_v1.0.3
bld/namelist_files/use_cases/2000_cam6_noresm.xml
bld/namelist_files/use_cases/2000_cam6_noresm_frc2.xml
cime_config/config_component.xml
cime_config/config_pes.xml
src/NorESM/micro_mg2_0.F90
```

The micro_mg2_0.F90 change fixes a Fortran logic bug that would sometimes cause a model crash.

```
$ git diff --name-only cam_cesm2_1_rel_05-Nor_v1.0.3 cam_cesm2_1_rel_05-Nor_v1.0.4
README.md
cime_config/config_component.xml
```

**Comment by gold2718** [comment]
We also need a description of cam_cesm2_1_rel_05-Nor_v1.0.5

Maybe: Add SSP5-3.4 and emission driven SSP compsets ?
```
$ git diff --name-only cam_cesm2_1_rel_05-Nor_v1.0.4 cam_cesm2_1_rel_05-Nor_v1.0.5
README.md
bld/namelist_files/use_cases/ssp126_cam6_noresm_frc2ext.xml
bld/namelist_files/use_cases/ssp534_cam6_noresm_frc2.xml
bld/namelist_files/use_cases/ssp534_cam6_noresm_frc2ext.xml
bld/namelist_files/use_cases/ssp534esm_cam6_noresm_frc2.xml
bld/namelist_files/use_cases/ssp585_cam6_noresm_frc2ext.xml
bld/namelist_files/use_cases/ssp585esm_cam6_noresm_frc2.xml
cime_config/config_component.xml
src/chemistry/oslo_aero/ndrop.F90
src/physics/cosp2/optics/cosp_optics.F90
```
ndrop.F90 and cosp_optics.F90 come from work done in the cam-Nor-dev branch.

**Comment by DirkOlivie** [comment]
Hi Steve,

yes, for the change from cam_cesm2_1_rel_05-Nor_v1.0.3 to cam_cesm2_1_rel_05-Nor_v1.0.4, the mentioning of the change in micro_mg2_0.F90 is maybe good.

For the change from cam_cesm2_1_rel_05-Nor_v1.0.4 to cam_cesm2_1_rel_05-Nor_v1.0.5 :
- new SSP5-3.4 compsets and emission driven SSP compsets
- technical (non answer-changing) modifications in CAM-Nor : correction in CCN (ndrop.F90) and COSP (cosp_optics.F90) diagnostics
- correction in H2O emission file link for f09 for the extended (year 2100-2300) SSP1-2.6 and SSP5-8.5 compsets

Dirk
