### ISSUE TITLE
Implement Oslo-aero in noresm_develop

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/CAM#89]
### What is the feature/what would you like to discuss?

As part of the development of the next version of NorESM, re-implement the Oslo-aero aerosol scheme using the new aerosol object types.`aerosol_properties` and `aerosol_state`.

### Is there anyone in particular you want to be part of this conversation?

@ingvi

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

No

**Comment by mvertens** [comment]
This was address in PR #98
