### ISSUE TITLE
Restore pp_trop_mam_oslo

### ISSUE THREAD

**Issue by gold2718** [NorESMhub/CAM#90]
### What is the feature/what would you like to discuss?

As part of building the new CAM-Nor version, pp_trop_mam_oslo needs to be restored or re-implemented from the noresm2 version.

Given that the chemistry pre-processor has changed, it will probably be necessary to regenerate the source code using the new pre-processor version. This will be done unless a test shows no source-code change.

There is not a lot of history of pp_trop_mam_oslo in this repository, however, the relevant comments in the log record will be copied into the log for this work.

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

**Comment by oyvindseland** [comment]
I presume this work is already done so this issue can be closed? @gold2718

**Comment by gold2718** [comment]
Yes, this was completed by #98, thanks for following up.
